---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCE8/x3QALb/+5vyx5ZnGYE8hCSOir5M6ujPNP1kJ2cGwz3XsZjgUurSa9laTGgSNNcge8Xu+OgKVW31PzmCT3tI07WUXDzBvHHyWS4lwZt0xgoOV5s+Kn2T4LP8CCJUgmSURY97Qx4x+gG8GutbWyhWapZ1wny/krx2Ktj0JdwcTi7K2ESsXGFiv3ncdh/8sOabK/4pXFH QfEmOO2v5RVxS4nSqm2igsAyUynIXEkXOWJRGAFC2NzRgdK4JVo1ou32OnpFygy3kNJsX6nmqzITcyn4byS1rWbiv7wT/NhV4pQT8JldY1uC5vnQfJW+XceQ8ojWj0MBesIIOOpG+xi6pS9w1X9nhIHqYcfq0AYHiPWl2v+EX7MgGZUq5Y0LYSKfaOfixRyYuSD8tLwReLadJuB6ElHIfZh3Oeh7hZ93FvTrQcocsZIqLUNg9mg1a+VObxS+g0CesjIAlW1kYbOne7XmLjFqRA6cfwHWpYNi5o4yH51GxqKOJ91pKsZ0FHWxw0KQezYG3FpJRBQxnYYJXrtFPIHJoZ+a6OkLJvWvNGzT769r12eOhCKYN/i3IXxMNFsAHMLzPestj9sIYbiy9i9zEIr28F+B8wOwy3afNpokMA0S/+ZKqzVkiabRCUlNjsnqWpDbdPGIK9GCE/t1zOMlHO9UUQwXX+RhgY2DnzeaSm1R8twjW6pcGh/XQqAeChsaw4EjjMXKpX/aVPpaVHC/B2UpppnAMAmJ2WQum5cLoOxMIcbZJKvWOtXyxiSY4+bniXoPwdMV+T3h2o2eyylDQ==
  template:
    metadata:
      name: backend-secrets
      namespace: default
