---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCWTa9KNiEkl757cMttkK3oIumtrhmjikMCqj41QrtL3lMaKgYA1fRA+F6Huoib2SNO81DIXuv0HU+UZ1pDlc+jw6cwSy3AL2DcmpQ0koh+VKxmlA5JnQNg9pO4bHBas/dwe+xzurDdtLT+8tV0C8kNEOIavPrkqenJI84tzaEFvOdNswB71VPKaCAgcLn13XR/nayQTt0+lw/Jx5b3Cw44x4FUayKosVntGrH+taxRl0HK7Jd/yNp9HOWvYbigEZBPQXtoLXON5mx+AaNn+x0hLBm6LGKCWbuKORKdGKBj1QoyIE2q9qfFjQnz0cRAq7hAKGHxtze77CgUSS+bIB5wxbVo27LwF1PFKivOSIw9amqicufjuZbgx8FlCysy81lqj5RZrBKPTN5S7/LizX67YzXDtA62vpdwiZ7+F6tEHf1OCHvRkgstcj1zCQy5FJPrdjVIpPzWOxpPg/8twVS4LrQXPGvvIdtT8rUUPwMK3LqsyBToKmf68++u6NigMgk7WKfy04uNeleMeB10ZQZvQDWE+kW6+vdUTGcjqXScFhH0ll2a4kSSs6BHHrNMFnyrEaWdiWoo2Cjl3iySqgZ7+as5BHhpxArNf7+dV4vANm35FhwXbCTVOYU2TST7Amli5vhvd5A36i2Rqm21K3GrOtymhHq8kHPUTRyK+TVlCahGe+yqpKfIHuuHiY1Rh/DXLCX1KSu4QGrHcuU5oYk3N/h0QzsMP+JZlRGxK2Q2LiXaGn6NEGGBRysaaySxlYNglesEgXvPqdG4Kv1n+FFnp+zmnQ==
  template:
    metadata:
      name: backend-secrets
      namespace: default
